server:
    port: ${CUSTOM.SERVER.PORT:9002}
eureka:
    instance:
     prefer-ip-address: true
     lease-expiration-duration-in-seconds: 30
    client:
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
        fetchRegistry: true
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: jovc
            #username: ''
            #password: ''
            uri: mongodb://localhost:27017
            authentication-database: admin
