server:
    port: ${CUSTOM.SERVER.PORT:9004}
eureka:
    client:
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
spring:
    data:
        mongodb:
            host: 192.168.226.134
            port: 27017
            database: jovc
            #username: ''
            #password: ''
            uri: mongodb://192.168.226.134:27017
            authentication-database: admin
