server:
    port: ${CUSTOM.SERVER.PORT:9004}
eureka:
    instance:
     prefer-ip-address: true
     lease-expiration-duration-in-seconds: 30
    client:
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
        fetchRegistry: true
        healthcheck:
         enable: true
        refresh:
         enable: true
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: jovc
            #username: ''
            #password: ''
            uri: mongodb://localhost:27017
            authentication-database: admin
            
info:
 app:
  app-name: Microservicio User Service
  description: Módulo de la arquitectura que disponibiliza informacion de los Usuarios
  version: 1.0.0.-SNAPSHOT

management:
 audievents:
  enable: true
 endpoints:
  web:
   exposure:
    include: '*'
   base-path: /actuator
 endpoint:
  health:
   group:
    custom:
     include: diskSpace, ping
     show-component: always
     show-details: always
 info:
  env:
   enabled: true
 health:
  env:
   enabled: true
